FROM ubuntu:latest

#apt packages

RUN apt-get update && apt-get install -y apache2 \
    libapache2-mod-wsgi-py3 \
    build-essential \
    libssl-dev \
    libffi-dev 
RUN apt-get install -y python3 \
    python3-venv \
    vim \
    sudo \
    python3-psycopg2

EXPOSE 80


ENTRYPOINT ["/bin/sh", "/var/www/app/chia-pools-api/startup.sh"]